### ISSUE TITLE
候选词不能居中显示～

### ISSUE THREAD

**Issue by superleeyom** [intret/PureBlue#1]
![](https://ws1.sinaimg.cn/large/006tNc79ly1fq3w2p5hk9j30lg06eq31.jpg)
- 强迫症患者没法适应。
- 候选词的上面留空太多了，不怎么美观，可以考虑居中显示。
- 可以考虑出一个居中版本的。

**Comment by intret** [comment]
@wangleeyom 已经新增了候选词居中的版本

**Comment by superleeyom** [comment]
多谢了，已经用上了，很棒，辛苦了。
